name: flutter_and_mapbox
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  mapbox_gl: ^0.9.0

  # You can use the latest library versions provided in the links
  # - pub.dev/packages/flutter_map/install
  # - pub.dev/packages/user_location/install

  flutter_map: any
  user_location: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


